---
Name: environmentcheckroutes
---
SilverStripe\Control\Director:
  rules:
    'health/check': 'Silverstripe\EnvironmentCheck\Controllers\DevHealthController'
    'dev/check/$Suite': 'Silverstripe\EnvironmentCheck\Controllers\DevCheckController'

