---
Name: environmentcheckroutes
---
SilverStripe\Control\Director:
  rules:
    'health/check': 'Silverstripe\EnvironmentCheck\Controllers\DevHealthController'

SilverStripe\Dev\DevelopmentAdmin:
  controllers:
    check:
      class: Silverstripe\EnvironmentCheck\Controllers\DevCheckController
      description: 'Run registered environment checks and display their status'

---
Name: environmentcheckroutes-dev_urls-confirmation-exceptions
After:
  - 'dev_urls-confirmation-middleware'
---
SilverStripe\Core\Injector\Injector:
  DevUrlsConfirmationMiddleware:
    properties:
      Bypasses:
        - '%$SilverStripe\Control\Middleware\ConfirmationMiddleware\UrlPathStartsWith("dev/check")'
